name: Night Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/fastapi-app:latest .
          docker push your-dockerhub-username/fastapi-app:latest

  tests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Run Tests
        run: |
          docker-compose up -d
          sleep 10
          docker-compose exec web pytest tests/

        env:
          DATABASE_URL: "postgresql://postgres:testpass@db:5432/bookly"

      - name: Notify if tests fail
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"email":"your-email@example.com", "message":"Nightly build failed!"}' https://your-notification-service.com/send