name: Night Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files in repository (Debugging)
        run: ls -R

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t shuqingzou/fastapi-app:latest .
          docker push shuqingzou/fastapi-app:latest

  tests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Run Tests
        run: |
          docker compose up -d
          sleep 10
          docker-compose exec web pytest tests/

        env:
          DATABASE_URL: "postgresql://postgres:testpass@db:5432/bookly"

      - name: Notify if tests fail
        if: failure()
        run: |
          chmod +x ./src/mail.py
          python3 ./src/mail.py "Nightly Build Failed" "Your nightly build has failed. Please check logs." "bryana.fay71@ethereal.email"